#ifndef ENEMIES_ARCHER_HPP
#define ENEMIES_ARCHER_HPP

#include "Bot.hpp"

namespace json_autogenerated_classes {
    struct Archer;
} // namespace json_autogenerated_classes
namespace json_models = json_autogenerated_classes;

namespace Enemies {

class Archer final : public Bot {
public:

    static Archer* create(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::Archer * model);

    [[nodiscard]] bool init() override;
    
    void update(float dt) override;

/// Bot interface

    void OnEnemyIntrusion() override;

    void OnEnemyLeave() override;

    /**
     * Generate projectile at unit's center 
     */
    void Attack() override;

private:
    enum WeaponClass{ RANGE };

    Archer(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::Archer * model);

/// Bot interface
   
    void UpdateState(const float dt) noexcept override;

    void UpdateAnimation() override;

    void OnDeath() override;
    
    void AddPhysicsBody() override;

    void AddAnimator() override;

    void AddWeapons() override;

    bool NeedAttack() const noexcept override;

/// Configs (Json Model Data):
    json_models::Archer const *const m_model { nullptr };
};

} // namespace Enemies 

#endif // ENEMIES_ARCHER_HPP 