#ifndef ENEMIES_AX_WARRIOR_HPP
#define ENEMIES_AX_WARRIOR_HPP

#include "Warrior.hpp"

namespace json_autogenerated_classes {
    struct AxWarrior;
} // namespace json_autogenerated_classes
namespace json_models = json_autogenerated_classes;

namespace Enemies {

class AxWarrior : public Warrior {
public:
    static AxWarrior* create(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::AxWarrior * model);

    bool init() override;

private:
    enum WeaponClass { MELEE };

    AxWarrior(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::AxWarrior * model);

    void AddWeapons() override;

    void Attack() override;
    
private:
/// Configs (Json Model Data):
    const json_models::AxWarrior * const m_model { nullptr };
};

} // namespace Enemies

#endif // ENEMIES_AX_WARRIOR_HPP