#ifndef ENEMIES_FIRECLOUD_HPP
#define ENEMIES_FIRECLOUD_HPP

#include "Bot.hpp"
#include "Utils.hpp"

namespace json_autogenerated_classes {
    struct UnitsFirecloud;
} // namespace json_autogenerated_classes
namespace json_models = json_autogenerated_classes;

namespace Enemies {

class FireCloud final : public Bot {
public:

    static FireCloud* create(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::UnitsFirecloud *model);

    [[nodiscard]] bool init() override;
    
    void update(float dt) override;

/// Bot interface

    void OnEnemyIntrusion() override;

    void OnEnemyLeave() override;

    /**
     * Generate projectile at unit's center 
     */
    void Attack() override;

private:
    enum WeaponClass{ RANGE };

    FireCloud(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::UnitsFirecloud *model);

/// Bot interface
   
    void UpdateState(const float dt) noexcept override;

    void UpdateAnimation() override;

    void UpdateWeapons(const float dt) noexcept override;

    void UpdatePosition(const float dt) noexcept override;

    void TryAttack() override;

    void OnDeath() override;
    
    void AddPhysicsBody() override;

    void AddAnimator() override;

    void AddWeapons() override;

    bool NeedAttack() const noexcept override;

private:

    bool m_finished { false };

    float m_lifetime { 0.f };

    float m_shellRenewTimer { 0.f };

    int m_shells { 0 };

/// Configs (Json Model Data):
    const json_models::UnitsFirecloud * const m_model { nullptr };
};

} // namespace Enemies 

#endif // ENEMIES_FIRECLOUD_HPP 