#ifndef ENEMIES_SPEAR_MAN_HPP
#define ENEMIES_SPEAR_MAN_HPP

#include "Warrior.hpp"

namespace json_autogenerated_classes {
    struct Spearman;
} // namespace json_autogenerated_classes
namespace json_models = json_autogenerated_classes;

namespace Enemies {

class Spearman : public Warrior {
public:
    static Spearman* create(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::Spearman * spearman);

    bool init() override;

private:
    enum WeaponClass { MELEE };

    Spearman(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::Spearman * spearman);

    void AddWeapons() override;

    void Attack() override;
    
private:
/// Configs (Json Model Data):
    const json_models::Spearman * const m_spearman { nullptr };
};

} // namespace Enemies

#endif // ENEMIES_SPEAR_MAN_HPP