#ifndef ENEMY_WASP_HPP
#define ENEMY_WASP_HPP

#include "Warrior.hpp"

namespace json_autogenerated_classes {
    struct Wasp;
} // namespace json_autogenerated_classes
namespace json_models = json_autogenerated_classes;

namespace Enemies {

class Wasp : public Warrior {
public:
    static Wasp* create(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::Wasp *model);

    bool init() override;

    void AttachNavigator(Path&& path) override;

private:
    enum WeaponClass { MELEE };

    Wasp(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::Wasp *model);

    void AddWeapons() override;

    void OnEnemyIntrusion() override;

    void OnEnemyLeave() override;

    bool NeedAttack() const noexcept override;

    void Attack() override;

    void Pursue(Unit * target) noexcept override;

    void AddPhysicsBody() override;

    void MoveAlong(Movement::Direction) noexcept override;

private:
/// Configs (Json Model Data):
    const json_models::Wasp * const m_model { nullptr };
};

} // namespace Enemies
#endif // ENEMY_WASP_HPP