#ifndef ENEMIES_WOLF_HPP
#define ENEMIES_WOLF_HPP

#include "Warrior.hpp"

namespace json_autogenerated_classes {
    struct Wolf;
} // namespace json_autogenerated_classes
namespace json_models = json_autogenerated_classes;

namespace Enemies {

class Wolf : public Warrior {
public:
    static Wolf* create(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::Wolf *model);

    bool init() override;

private:
    enum WeaponClass { MELEE };

    Wolf(size_t id
        , const cocos2d::Size& contentSize
        , const json_models::Wolf *model);

    void AddWeapons() override;

    void Attack() override;

    void OnEnemyIntrusion() override;

    void OnEnemyLeave() override;

    bool NeedAttack() const noexcept override;

private:

/// Configs (Json Model Data):
    const json_models::Wolf * const m_model { nullptr };
};

} // namespace Enemies

#endif // ENEMIES_WOLF_HPP